analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.inject.dart
    - lib/**.inject.summary
linter:
  rules:
    public_member_api_docs: false
    depend_on_referenced_packages: false
    lines_longer_than_80_chars: false
    avoid_unused_constructor_parameters: false
    sort_pub_dependencies: false
