name: design_system
description: Package in charge of storing the forest design system.
version: 11.7.0+0
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Phone Input Field
  intl_phone_field: 3.2.0
  libphonenumber_plugin: 0.3.3

  # Animations
  lottie: 3.3.2

  # SVG
  flutter_svg: 2.2.1

  # Pinput
  pinput: 5.0.0

  # Progress Animated Bar (Should be replaced by us)
  # flutter_animation_progress_bar: ^2.3.1
  simple_animation_progress_bar: 1.8.2

  # Markdown
  flutter_markdown: 0.7.7+1

  equatable: 2.0.7

  shared_dependencies:
    path: ../shared_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.0
  very_good_analysis: 5.1.0

flutter:
  uses-material-design: true
