name: drunk_test_demo
description: "Drunk cyclist test demo (Flutter web)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bloc: 9.0.0
  side_effect_cubit: 1.0.1
  equatable: 2.0.7
  flutter_svg: 2.2.1
  clock: ^1.1.1
  url_launcher: ^6.3.0
  blur: 4.0.0
  supabase_flutter: ^2.8.0
  shared_preferences: ^2.3.2
  uuid: 4.5.2

  design_system:
    path: packages/design_system
  shared_dependencies:
    path: packages/shared_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  bloc: 9.0.0
  flutter_bloc: 9.0.0
  analyzer: 8.1.1
  dart_style: 3.0.1
  device_info_plus: 12.1.0
  get_it: 8.2.0
  js: 0.7.1
  photo_view: 0.15.0
  test_api: 0.7.7

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: Mohr
      fonts:
        - asset: assets/fonts/Mohr-BlackIt.otf
          weight: 900
    - family: GT
      fonts:
        - asset: assets/fonts/GT-Haptik-Regular.ttf
          weight: 400
        - asset: assets/fonts/GT-Haptik-Bold.ttf
          weight: 700
