name: shared_dependencies
description: Package in charge of storing third-party libraries shared between different modules.
version: 11.7.0+0
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Functional Programming
  equatable: 2.0.7
  oxidized: 6.2.0

  # Routing and Dependency Injection
  flutter_modular: 6.3.4

  # Network
  dio: 5.8.0+1

  geojson_vi: 2.2.5
  uuid: 4.5.2

dependency_overrides:
  bloc: 9.0.0
  flutter_bloc: 9.0.0
  analyzer: 8.1.1
  dart_style: 3.0.1
  device_info_plus: 12.1.0
  get_it: 8.2.0
  js: 0.7.1
  photo_view: 0.15.0
  test_api: 0.7.7

dev_dependencies:
  mocktail: 1.0.0
  test: 1.26.3
  very_good_analysis: 5.1.0
